### ISSUE TITLE
Adding the generic WVGA, FWVGA, HVGA

### ISSUE THREAD

**Issue by arLevi** [paranoida/sass-mediaqueries#26]
Will it be possible to add the Android's templates of: WVGA, FWVGA, HVGA etc .. ?
And their orientation just like your did for the iOS ?

I find it very difficult to implement them using your lib, because I need both width & height to nail a device.
Otherwise, the width of 480px will match X in portrait, but won't match 480px in landscape for template Y.

Thanks.

**Comment by paranoida** [comment]
You can do it with the new generator.
