### ISSUE TITLE
Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 144dpi)

### ISSUE THREAD

**Issue by lpsBetty** [paranoida/sass-mediaqueries#28]
I get the following console warning:

Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min-resolution: 144dpi)

Is it better to use dppx instead of dpi?

**Comment by paranoida** [comment]
Cant see anything in my console. Could you provide with jsfiddle or codepen?

Thanks.

**Comment by lpsBetty** [comment]
Sorry, I had another external CSS file included which caused the warning (chosen.css)
