### ISSUE TITLE
Enhancement: 'iPhone All' would be nice to have

### ISSUE THREAD

**Issue by wootwoot1234** [paranoida/sass-mediaqueries#31]
Or is there an easy sass way to do it?

**Comment by paranoida** [comment]
I would use `max-screen(width)` mixin where you can assume that maximum device with is `736px`. should work for all iphones.

**Comment by wootwoot1234** [comment]
@paranoida good tip, thanks!  Works great.  I think it would be great to have that as AlliPhones so I don't need to look up this thread every time I need to do it. :)

**Comment by paranoida** [comment]
It's related to: https://github.com/paranoida/sass-mediaqueries/issues/32

I just cant see the perfect approach
