### ISSUE TITLE
v1.6.0 is not compatible with libsass

### ISSUE THREAD

**Issue by Igloczek** [paranoida/sass-mediaqueries#35]
Looks like v1.6.0 is not compatible with libsass. 
You can try here http://sassmeister.com/ - open control panel and you can easly jump between versions.

Console error:
```
assets/styles/common/_mixins.scss
  45:15  mixin mq has no parameter named $min-width
assets/styles/common/_mixins.scss
  45:15  mixin mq has no parameter named $min-width
```

**Comment by paranoida** [comment]
You are right :/ will investigate it

Thanks

**Comment by paranoida** [comment]
Fixed. Problem was with parsing arguments. Should be fine now :+1: 

It would be great if you could test it.

**Comment by Igloczek** [comment]
Work like a charm, thanks! :+1:
