### ISSUE TITLE
1.6 does not seem to compile with libsass

### ISSUE THREAD

**Issue by ZeeCoder** [paranoida/sass-mediaqueries#36]
It would be nice to have a warning about which SASS version is needed for compilation.
I use gulp-sass, which uses node-sass, which uses libsass:

Libsass is written in C, and although it's quite fast, it's slow to implement new functionalities, like it's ruby-based counterpart.

I got the following error, after upgrading to 1.6 from 1.4, and I think it's caused by libsass' implementation:
``` js
{ [Error: expected '{' in media query]
  message: 'expected \'{\' in media query',
  fileName: './front_src/bower_components/sass-mediaqueries/_media-queries.scss',
  lineNumber: 29,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass',
  __safety: { toString: [Function] } }
```

**Comment by paranoida** [comment]
Which version of `libasass` are you using?

**Comment by ZeeCoder** [comment]
node-sass: 2.1.1
libsass: 3.1.0

**Comment by paranoida** [comment]
It was a bug in libsass: 
- https://github.com/sass/libsass/issues/358
- https://github.com/sass/libsass/issues/346

it seems to be fixed in `3.2`. 

Not sure if I can display any warning here.

**Comment by ZeeCoder** [comment]
Thanks for the quick responses, I got it sorted out!
My Yeoman generator installed an "old" version of the gulp-sass plugin: 1.something instead of the newest 2.x versions, which include the newer libsass versions.

Once I upgraded it, everything compiled without any problems, thanks again! :+1:

**Comment by paranoida** [comment]
:+1:
